### ISSUE TITLE
Scrape the legislative data and upload it to s3

### ISSUE THREAD

**Issue by eluciano11** [Code4PuertoRico/paravotar-api#3]
Scrape the legislative ballots from [CEE](http://ww2.ceepur.org/es-pr/Eventos%20Electorales/Paginas/Papeletas-Modelo---Elecciones-Generales-2016.aspx).

The JSON should have the precent number as they key and an object with the ballot and town name as the value. The expected JSON should look like this:

```json
{
  "082": {
      "townName": "Caguas",
      "ballot": "<link to PDF>",
      "ballotData": "<link to JSON data extractor>"
   }
}
```

- Link to PDF found on site.
- Link to JSON extractor will be provided later

**Comment by Jpadilla1** [comment]
This is done
