### ISSUE TITLE
Scrape municipal ballots data

### ISSUE THREAD

**Issue by eluciano11** [Code4PuertoRico/paravotar-api#4]
Scrape the municipal ballots from [CEE](http://ww2.ceepur.org/es-pr/Eventos%20Electorales/Paginas/Papeletas-Modelo---Elecciones-Generales-2016.aspx).

The JSON should have the precent number as they key and an object with the ballot and town name as the value. The expected JSON should look like this:

```json
{
  "caguas": {
     "ballot": "link-to-ballot.pdf" ,
     "ballotData": { ... }
   }
}
```

**Comment by Jpadilla1** [comment]
This is done
